# Generated by Django 3.1.2 on 2021-09-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_Name', models.CharField(max_length=100)),
                ('Player_Email', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('No_of_Games', models.IntegerField()),
                ('Total_Score', models.IntegerField()),
            ],
            options={
                'db_table': 'Players',
            },
        ),
    ]
